### ISSUE TITLE
recurrent KeyError: 'pdfminer.six' issue in a python 3.11 environment

### ISSUE THREAD

**Issue by peutch** [realiti4/pip-upgrade#19]
Hi,

The affected system is:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
$ python --version
Python 3.11.2
$ pip --version
pip 25.1.1 from /srv/backup/local/python3.11_venv/jupyterlab/lib/python3.11/site-packages/pip (python 3.11)
$ pip show pip-upgrade-tool
Name: pip-upgrade-tool
Version: 0.7.4
Summary: An easy tool for upgrading all of your packages while not breaking dependencies
Home-page: https://github.com/realiti4/pip-upgrade
Author: Onur Cetinkol
Author-email: realiti44@gmail.com
License: 
Location: /srv/backup/local/python3.11_venv/jupyterlab/lib/python3.11/site-packages
Requires: packaging
Required-by: 
```

And here's what happens most of the time pip_upgrade is executed but strangely not always even if pdfminer.six is installed:

```
$ pip-upgrade
Checking outdated packages...
Skipping pdfminer.six, warning: Name mismatch. This will be improved. Manually upgrade if needed
Skipping pdfminer.six, warning: Name mismatch. This will be improved. Manually upgrade if needed
ERROR:root:An exception was thrown!
Traceback (most recent call last):
  File "/srv/backup/local/python3.11_venv/jupyterlab/lib/python3.11/site-packages/pip_upgrade/dependencies_base.py", line 36, in get_dependencies
    pkg_store = self.dict[pkg_name]
                ~~~~~~~~~^^^^^^^^^^
KeyError: 'pdfminer.six'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/backup/local/python3.11_venv/jupyterlab/lib/python3.11/site-packages/pip_upgrade/dependencies_base.py", line 39, in get_dependencies
    pkg_store = self.dict[pkg_name.lower()]
                ~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'pdfminer.six'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/backup/local/python3.11_venv/jupyterlab/lib/python3.11/site-packages/pip_upgrade/main.py", line 49, in main
    pip_upgrade.get_dependencies()
  File "/srv/backup/local/python3.11_venv/jupyterlab/lib/python3.11/site-packages/pip_upgrade/dependencies_base.py", line 46, in get_dependencies
    raise e
  File "/srv/backup/local/python3.11_venv/jupyterlab/lib/python3.11/site-packages/pip_upgrade/dependencies_base.py", line 44, in get_dependencies
    pkg_store = self.dict[pkg_name]
                ~~~~~~~~~^^^^^^^^^^
KeyError: 'pdfminer.six'
```

Any idea?

**Comment by psec9000** [comment]
Same with python 3.14.2 on windows 11.
Also, some of the packages proposed for upgrade are going to break requirements of other packages.

**Comment by realiti4** [comment]
Sorry for the delay! Key error fixed in b634e627a1c897f7cce1d28a871233dd1e0631e8 

I am also publishin as v1.0.1. Please let me know if you have any issues.

**Comment by psec9000** [comment]
Thanks for the update!
I still get the Key error (I am using the --no-venv flag by the way).

**Comment by realiti4** [comment]
> Thanks for the update! I still get the Key error (I am using the --no-venv flag by the way).

Is the issue with the same package pdfminer.six? Also you are on 1.0.1 right? Could you share your env with pip freeze or something please?

**Comment by psec9000** [comment]
The issue is with jaraco-classes.
Pip still installs 1.0.0, so I rebuild the package from checkout b634e62.
Sorry, the env is quite big:

accelerate==1.12.0
aiohappyeyeballs==2.6.1
aiohttp==3.13.3
aiosignal==1.4.0
alabaster==1.0.0
altgraph==0.17.5
anyio==4.12.1
argon2-cffi==25.1.0
argon2-cffi-bindings==25.1.0
arrow==1.4.0
astroid==4.0.3
asttokens==3.0.1
async-lru==2.0.5
asyncssh==2.22.0
atomicwrites==1.4.1
attrs==25.4.0
autopep8==2.0.4
babel==2.17.0
bcrypt==5.0.0
beautifulsoup4==4.14.3
binaryornot==0.4.4
black==25.12.0
bleach==6.3.0
cattrs==25.3.0
certifi==2026.1.4
cffi==2.0.0
chardet==5.2.0
charset-normalizer==3.4.4
click==8.3.1
cloudpickle==3.1.2
colorama==0.4.6
comm==0.2.3
contourpy==1.3.3
cookiecutter==2.6.0
cryptography==46.0.3
cycler==0.12.1
debugpy==1.8.19
decorator==5.2.1
defusedxml==0.7.1
diff-match-patch==20241021
dill==0.4.0
docstring-to-markdown==0.17
docutils==0.22.4
et_xmlfile==2.0.0
executing==2.2.1
fastjsonschema==2.21.2
filelock==3.20.2
flake8==7.1.2
fonttools==4.61.1
fqdn==1.5.1
frozenlist==1.8.0
fsspec==2025.12.0
h11==0.16.0
hf-xet==1.2.0
httpcore==1.0.9
httpx==0.28.1
huggingface-hub==0.36.0
idna==3.11
imagesize==1.4.1
importlib_metadata==8.7.1
inflection==0.5.1
intervaltree==3.2.1
IPTCInfo3==2.3.0
ipykernel==6.31.0
ipython==9.9.0
ipython_pygments_lexers==1.1.1
ipywidgets==8.1.8
isoduration==20.11.0
isort==7.0.0
jaraco.classes==3.4.0
jaraco.context==6.0.2
jaraco.functools==4.4.0
jedi==0.19.2
jellyfish==1.2.1
Jinja2==3.1.6
json5==0.13.0
jsonpointer==3.0.0
jsonschema==4.26.0
jsonschema-specifications==2025.9.1
jupyter==1.1.1
jupyter-console==6.6.3
jupyter-events==0.12.0
jupyter-lsp==2.3.0
jupyter_client==8.8.0
jupyter_core==5.9.1
jupyter_server==2.17.0
jupyter_server_terminals==0.5.3
jupyterlab==4.5.1
jupyterlab_pygments==0.3.0
jupyterlab_server==2.28.0
jupyterlab_widgets==3.0.16
keyring==25.7.0
kiwisolver==1.4.9
lark==1.3.1
lsprotocol==2025.0.0
markdown-it-py==4.0.0
MarkupSafe==3.0.3
matplotlib==3.10.8
matplotlib-inline==0.2.1
mccabe==0.7.0
mdurl==0.1.2
mistune==3.2.0
more-itertools==10.8.0
mpmath==1.3.0
multidict==6.7.0
mypy_extensions==1.1.0
nbclient==0.10.4
nbconvert==7.16.6
nbformat==5.10.4
nest-asyncio==1.6.0
networkx==3.6.1
notebook==7.5.1
notebook_shim==0.2.4
Nuitka==2.8.9
numpy==2.4.0
numpydoc==1.10.0
openpyxl==3.1.5
ordered-set==4.1.0
outcome==1.3.0.post0
packaging==25.0
pandas==2.3.3
pandocfilters==1.5.1
parso==0.8.5
pathspec==1.0.2
pdfrw==0.4
pefile==2024.8.26
pexpect==4.9.0
pickleshare==0.7.5
pillow==12.1.0
pip-upgrade-tool==1.0.0
platformdirs==4.5.1
pluggy==1.6.0
prometheus_client==0.23.1
prompt_toolkit==3.0.52
propcache==0.4.1
protobuf==6.33.2
psutil==7.2.1
ptyprocess==0.7.0
pure_eval==0.2.3
pyarmor==9.2.3
pyarmor.cli.core==8.1.0
pycodestyle==2.12.1
pycparser==2.23
pydocstyle==6.3.0
pyflakes==3.2.0
PyGithub==2.8.1
Pygments==2.19.2
pyinstaller==6.17.0
pyinstaller-hooks-contrib==2025.11
PyJWT==2.10.1
pylint==4.0.4
pylint-venv==3.0.4
pyls-spyder==0.4.0
PyNaCl==1.6.2
pyparsing==3.3.1
PyQt5==5.15.11
PyQt5-Qt5==5.15.2
PyQt5_sip==12.17.2
PyQtWebEngine==5.15.7
PyQtWebEngine-Qt5==5.15.2
pyserial==3.5
PySocks==1.7.1
python-dateutil==2.9.0.post0
python-json-logger==4.0.0
python-lsp-black==2.0.0
python-lsp-jsonrpc==1.1.2
python-lsp-ruff==2.3.0
python-lsp-server==1.14.0
python-slugify==8.0.4
pytokens==0.3.0
pytoolconfig==1.3.1
pytz==2025.2
pyuca==1.2
pywin32==311
pywin32-ctypes==0.2.3
pywinpty==3.0.2
PyYAML==6.0.3
pyzmq==27.1.0
QDarkStyle==3.2.3
qstylizer==0.2.4
QtAwesome==1.4.0
qtconsole==5.7.0
QtPy==2.4.3
referencing==0.37.0
regex==2025.11.3
reportlab==4.4.7
requests==2.32.5
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rfc3987-syntax==1.1.0
rich==14.2.0
roman-numerals==4.1.0
rope==1.14.0
rpds-py==0.30.0
rtree==1.4.1
ruff==0.14.11
safetensors==0.7.0
scipy==1.16.3
selenium==4.39.0
Send2Trash==2.0.0
setuptools==80.9.0
shellingham==1.5.4
simpy==4.1.1
six==1.17.0
sniffio==1.3.1
snowballstemmer==3.0.1
sortedcontainers==2.4.0
soupsieve==2.8.1
Sphinx==9.1.0
sphinxcontrib-applehelp==2.0.0
sphinxcontrib-devhelp==2.0.0
sphinxcontrib-htmlhelp==2.1.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==2.0.0
sphinxcontrib-serializinghtml==2.0.0
spyder==6.1.2
spyder-kernels==3.1.2
stack-data==0.6.3
superqt==0.7.7
svgwrite==1.4.3
sympy==1.14.0
terminado==0.18.1
text-unidecode==1.3
textdistance==4.6.3
three-merge==0.1.1
tinycss2==1.4.0
tokenizers==0.22.2
tomlkit==0.13.3
torch==2.9.1+cu126
torchvision==0.24.1
tornado==6.5.4
tqdm==4.67.1
traitlets==5.14.3
transformers==4.57.3
trio==0.32.0
trio-websocket==0.12.2
typer-slim==0.21.1
typing_extensions==4.15.0
tzdata==2025.3
ujson==5.11.0
uri-template==1.3.0
urllib3==2.6.3
watchdog==6.0.0
wavedrom==2.0.3.post3
wcwidth==0.2.14
webcolors==25.10.0
webencodings==0.5.1
websocket-client==1.9.0
whatthepatch==1.0.7
wheel==0.45.1
widgetsnbextension==4.0.15
wsproto==1.3.2
xlsxwriter==3.2.9
yapf==0.43.0
yarl==1.22.0
zipp==3.23.0
zstandard==0.25.0

**Comment by psec9000** [comment]
Minimal venv to reproduce the problem:

jaraco.classes==3.4.0
more-itertools==10.8.0
packaging==25.0
pip-upgrade-tool @ file:///D:/data/src/python/_temp/pip-upgrade

**Comment by realiti4** [comment]
> Minimal venv to reproduce the problem:
> 
> jaraco.classes==3.4.0 more-itertools==10.8.0 packaging==25.0 pip-upgrade-tool @ file:///D:/data/src/python/_temp/pip-upgrade

Thanks! Yes you are right, the previous fix had an issue. Key error should be fixed with a6c87d8d79f114d6c52ae93eabf96029ce86b4f1 now. I also updated to 1.0.2, could you now test?

**Comment by psec9000** [comment]
Version 1.02 solved the key error, good.

Anyway I am not sure if all the suggested upagrades are safe - I'll run some tests and let you know.

**Comment by realiti4** [comment]
> Version 1.02 solved the key error, good.
> 
> Anyway I am not sure if all the suggested upagrades are safe - I'll run some tests and let you know.

Yes, that is a known issue since we are relying on pip's resolver for upgrades. Suggestion should be safe, however if their dependencies have higher minimum version requirement for one of the installed packages, that might upgrade further yes.

Currently we don't have a logic for when things can't be resolved. Ideally, we should be showing an error and not upgrading.

Your tests would be really helpful, thanks. Please let me know when you do.

**Comment by psec9000** [comment]
OK, I am reporting here a way to reproduce the problem.

Create a test venv:
  python -m venv test1
  cd test1
  Scripts\activate
  pip install setuptools pip-upgrade-tool spyder
  
Upgrade with pip-upgrade (or just upgrade autopep8 manually):
  pip-upgrade
  
Save the requirements and download the packages:
  pip freeze > requirements.txt
  mkdir wheelhouse
  pip download -r requirements.txt -d wheelhouse

Error:
ERROR: Cannot install autopep8==2.3.2 and python-lsp-server[all]==1.14.0 because these package versions have conflicting dependencies.

**Comment by realiti4** [comment]
> OK, I am reporting here a way to reproduce the problem.
> 
> Create a test venv: python -m venv test1 cd test1 Scripts\activate pip install setuptools pip-upgrade-tool spyder
> 
> Upgrade with pip-upgrade (or just upgrade autopep8 manually): pip-upgrade
> 
> Save the requirements and download the packages: pip freeze > requirements.txt mkdir wheelhouse pip download -r requirements.txt -d wheelhouse
> 
> Error: ERROR: Cannot install autopep8==2.3.2 and python-lsp-server[all]==1.14.0 because these package versions have conflicting dependencies.

Thanks for the test environment example, it was really helpful.

I see the issue, actually the suggestions were wrong like you said. Optional dependencies like autopep8 in python-lsp-server weren't taken into account by the tool. Now it respects if it sees autopep8 in the environment.

With this fix now your example returns 0 update suggestions just after installation like it should.

Could you test on master or the pre-release 1.1.0b1?

**Comment by psec9000** [comment]
1.1.0b1 updated many packages in my big production env without breaking any dependency, good job👍

Anyway it didn't update ALL the possible packages (in particular it skipped numpy and scipy).
This time I updated numpy and scipy manually, then tested the dependency system with this code:
   import pkg_resources
   pkg_resources.require(str(dep.as_requirement()) for dep in pkg_resources.working_set)

I'll try to come up with a test case soon, in the meantime thanks for the update.

**Comment by realiti4** [comment]
> 1.1.0b1 updated many packages in my big production env without breaking any dependency, good job👍
> 
> Anyway it didn't update ALL the possible packages (in particular it skipped numpy and scipy). This time I updated numpy and scipy manually, then tested the dependency system with this code: import pkg_resources pkg_resources.require(str(dep.as_requirement()) for dep in pkg_resources.working_set)
> 
> I'll try to come up with a test case soon, in the meantime thanks for the update.

Good to hear! Please let me know when your test case is ready, thanks.

**Comment by psec9000** [comment]
It's jupyterlab! May by due to this in the metadata "Requires-Dist: scipy==1.15.1"?
Try:
   pip install setuptools pip-upgrade-tool==1.1.0b1 scipy==1.16.3 jupyterlab

scipy can safely be updated, but it is not flagged by pip-upgrade 1.1.0b1

**Comment by realiti4** [comment]
> It's jupyterlab! May by due to this in the metadata "Requires-Dist: scipy==1.15.1"? Try: pip install setuptools pip-upgrade-tool==1.1.0b1 scipy==1.16.3 jupyterlab
> 
> scipy can safely be updated, but it is not flagged by pip-upgrade 1.1.0b1

Oh, respecting every optional dependency rule also makes this wrong.

As far as I can tell, there isn't a way to determine a package's extras flag from metadata after installation, unless we use something like the project's pyproject.toml like other package managers do.

That's why I will revert the default behavior to the previous one, because there can be many unrelated dependency flags for a package.

I'll think about what we can do about this, but for now I'm adding a new argument --respect-extras that will take into account optional dependencies, and it will work as 1.1.0b1 does. Would this work?

I published this as 1.1.0b2

**Comment by psec9000** [comment]
--respect-extras worked as expected .
I didn't try paranoid corner cases (e.g. starting from an env with violated requirements), but for me it is perfectly useble as is👍

**Comment by realiti4** [comment]
> --respect-extras worked as expected . I didn't try paranoid corner cases (e.g. starting from an env with violated requirements), but for me it is perfectly useble as is👍

I also tried something new for the extra detection. Could you try this argument with 1.1.0b3? It might work for all cases now.

pip-upgrade --experimental

**Comment by psec9000** [comment]
Still some problem with the extras, see below.
---
pip-upgrade --novenv --respect-extras
Checking outdated packages...
All packages are up to date! 🎉

pip-upgrade --novenv --experimental
Checking outdated packages...
These packages will be upgraded:  ['flake8', 'numpy', 'ruff', 'scipy']

My check:
pkg_resources.ContextualVersionConflict: (pyflakes 3.4.0 (c:\python314\lib\site-packages), Requirement.parse('pyflakes<3.3.0,>=3.2.0; extra == "all"'), {'python-lsp-server'})

**Comment by realiti4** [comment]
I decided to make the experimental mode the default. This mode assumes that if an extra tag has all of its dependencies listed under it, the main package was probably installed with that tag, so we respect those dependency rules.

So the default mode now works as a middle ground between --no-extras and --respect-extras.

I've updated the README with the new --respect-extras and --no-extras arguments and am publishing this as 1.1.0.

**Comment by realiti4** [comment]
I am closing this since key error is fixed in the last version.
